# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.srcs/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0.xci
# IP: The module: 'DMA_Design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.gen/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.gen/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.gen/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.srcs/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0.xci
# IP: The module: 'DMA_Design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.gen/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.gen/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.gen/sources_1/bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
