# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Clk_Div/Clk_Div.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clk_Div || ORIG_REF_NAME==Clk_Div} -quiet] -quiet

# IP: bd/Clk_Div/ip/Clk_Div_Clock_Divider_0_0/Clk_Div_Clock_Divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clk_Div_Clock_Divider_0_0 || ORIG_REF_NAME==Clk_Div_Clock_Divider_0_0} -quiet] -quiet

# IP: bd/Clk_Div/ip/Clk_Div_Clock_Divider_1_0/Clk_Div_Clock_Divider_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clk_Div_Clock_Divider_1_0 || ORIG_REF_NAME==Clk_Div_Clock_Divider_1_0} -quiet] -quiet

# IP: bd/Clk_Div/ip/Clk_Div_Clock_Divider_1_1/Clk_Div_Clock_Divider_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clk_Div_Clock_Divider_1_1 || ORIG_REF_NAME==Clk_Div_Clock_Divider_1_1} -quiet] -quiet

# IP: bd/Clk_Div/ip/Clk_Div_Clock_Divider_1_2/Clk_Div_Clock_Divider_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clk_Div_Clock_Divider_1_2 || ORIG_REF_NAME==Clk_Div_Clock_Divider_1_2} -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DEMO PT . III/PYNQ_DEMO PT . III.gen/sources_1/bd/Clk_Div/Clk_Div_ooc.xdc
