# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Adders_Constraints.xdc

# Block Designs: bd/Adder_Design/Adder_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design || ORIG_REF_NAME==Adder_Design} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_RC_Add_0_0/Adder_Design_RC_Add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_RC_Add_0_0 || ORIG_REF_NAME==Adder_Design_RC_Add_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_processing_system7_0_0/Adder_Design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_processing_system7_0_0 || ORIG_REF_NAME==Adder_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_axi_gpio_0_0/Adder_Design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_0 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_xbar_0/Adder_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_xbar_0 || ORIG_REF_NAME==Adder_Design_xbar_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_axi_interconnect_0_0/Adder_Design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_axi_interconnect_0_0 || ORIG_REF_NAME==Adder_Design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_rst_ps7_0_100M_0/Adder_Design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Adder_Design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_axi_gpio_0_1/Adder_Design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_1 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_axi_gpio_0_2/Adder_Design_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_2 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_2} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_auto_pc_0/Adder_Design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_auto_pc_0 || ORIG_REF_NAME==Adder_Design_auto_pc_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_s00_mmu_0/Adder_Design_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_s00_mmu_0 || ORIG_REF_NAME==Adder_Design_s00_mmu_0} -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_processing_system7_0_0/Adder_Design_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_processing_system7_0_0 || ORIG_REF_NAME==Adder_Design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_0/Adder_Design_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_0 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_0/Adder_Design_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_0/Adder_Design_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_0 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_rst_ps7_0_100M_0/Adder_Design_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Adder_Design_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_rst_ps7_0_100M_0/Adder_Design_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Adder_Design_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_1/Adder_Design_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_1 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_1/Adder_Design_axi_gpio_0_1_ooc.xdc

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_1/Adder_Design_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_1 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_2/Adder_Design_axi_gpio_0_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_2 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_2/Adder_Design_axi_gpio_0_2_ooc.xdc

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_axi_gpio_0_2/Adder_Design_axi_gpio_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_axi_gpio_0_2 || ORIG_REF_NAME==Adder_Design_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/ip/Adder_Design_auto_pc_0/Adder_Design_auto_pc_0_ooc.xdc

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO 6/PYNQ DEMO 6.gen/sources_1/bd/Adder_Design/Adder_Design_ooc.xdc
