# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/RGBCntrl/RGBCntrl.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGBCntrl || ORIG_REF_NAME==RGBCntrl} -quiet] -quiet

# IP: bd/RGBCntrl/ip/RGBCntrl_Clock_Divider_0_0_2/RGBCntrl_Clock_Divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGBCntrl_Clock_Divider_0_0 || ORIG_REF_NAME==RGBCntrl_Clock_Divider_0_0} -quiet] -quiet

# IP: bd/RGBCntrl/ip/RGBCntrl_RGBController_0_0_2/RGBCntrl_RGBController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGBCntrl_RGBController_0_0 || ORIG_REF_NAME==RGBCntrl_RGBController_0_0} -quiet] -quiet

# IP: bd/RGBCntrl/ip/RGBCntrl_RGBController_0_1/RGBCntrl_RGBController_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGBCntrl_RGBController_0_1 || ORIG_REF_NAME==RGBCntrl_RGBController_0_1} -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DEMO PT. IV/PYNQ_DEMO PT. IV.gen/sources_1/bd/RGBCntrl/RGBCntrl_ooc.xdc
