# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/CNTRL_Design/CNTRL_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNTRL_Design || ORIG_REF_NAME==CNTRL_Design} -quiet] -quiet

# IP: bd/CNTRL_Design/ip/CNTRL_Design_LED_Controller_0_0/CNTRL_Design_LED_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNTRL_Design_LED_Controller_0_0 || ORIG_REF_NAME==CNTRL_Design_LED_Controller_0_0} -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ DEMO PT. II/PYNQ DEMO PT. II.gen/sources_1/bd/CNTRL_Design/CNTRL_Design_ooc.xdc
