# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Adders_Constraints.xdc

# Block Designs: bd/Adder_Design/Adder_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design || ORIG_REF_NAME==Adder_Design} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_RC_Add_0_0/Adder_Design_RC_Add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_RC_Add_0_0 || ORIG_REF_NAME==Adder_Design_RC_Add_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_processing_system7_0_0/Adder_Design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_processing_system7_0_0 || ORIG_REF_NAME==Adder_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_xlslice_0_0/Adder_Design_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_xlslice_0_0 || ORIG_REF_NAME==Adder_Design_xlslice_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_xlslice_a_0/Adder_Design_xlslice_a_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_xlslice_a_0 || ORIG_REF_NAME==Adder_Design_xlslice_a_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_xlconcat_0_0/Adder_Design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_xlconcat_0_0 || ORIG_REF_NAME==Adder_Design_xlconcat_0_0} -quiet] -quiet

# IP: bd/Adder_Design/ip/Adder_Design_xlconstant_0_0/Adder_Design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_Design_xlconstant_0_0 || ORIG_REF_NAME==Adder_Design_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Adders/PYNQ Adders.gen/sources_1/bd/Adder_Design/ip/Adder_Design_processing_system7_0_0/Adder_Design_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Adder_Design_processing_system7_0_0 || ORIG_REF_NAME==Adder_Design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Adders/PYNQ Adders.gen/sources_1/bd/Adder_Design/Adder_Design_ooc.xdc
