# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DMA_Design/DMA_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design || ORIG_REF_NAME==DMA_Design} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_processing_system7_0_0/DMA_Design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_processing_system7_0_0 || ORIG_REF_NAME==DMA_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_axi_dma_0_0/DMA_Design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_axi_dma_0_0 || ORIG_REF_NAME==DMA_Design_axi_dma_0_0} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_auto_pc_0/DMA_Design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_auto_pc_0 || ORIG_REF_NAME==DMA_Design_auto_pc_0} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_ps7_0_axi_periph_0/DMA_Design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==DMA_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_rst_ps7_0_50M_0/DMA_Design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_rst_ps7_0_50M_0 || ORIG_REF_NAME==DMA_Design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_auto_pc_1/DMA_Design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_auto_pc_1 || ORIG_REF_NAME==DMA_Design_auto_pc_1} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_axi_mem_intercon_0/DMA_Design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_axi_mem_intercon_0 || ORIG_REF_NAME==DMA_Design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_auto_pc_2/DMA_Design_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_auto_pc_2 || ORIG_REF_NAME==DMA_Design_auto_pc_2} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_axi_mem_intercon_1_0/DMA_Design_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_axi_mem_intercon_1_0 || ORIG_REF_NAME==DMA_Design_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/DMA_Design/ip/DMA_Design_axis_data_fifo_0_0/DMA_Design_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_Design_axis_data_fifo_0_0 || ORIG_REF_NAME==DMA_Design_axis_data_fifo_0_0} -quiet] -quiet

# XDC: c:/Users/abous/OneDrive/Documents/GitHub/PYNQ Demo/PYNQ_DMA/PYNQ_DMA.gen/sources_1/bd/DMA_Design/DMA_Design_ooc.xdc
